// Query Graph
export const CHANGE_QUERY_GRAPH_TYPE = 'CHANGE_QUERY_GRAPH_TYPE'
export const CHANGE_QUERY_NUMBER_RELATIONS = 'CHANGE_QUERY_NUMBER_RELATIONS'
export const CHANGE_QUERY_GRAPH = 'CHANGE_QUERY_GRAPH'

// Algorithm
export const CHANGE_ALGORITHM = 'CHANGE_ALGORITHM'

// Variables
export const ADD_VARIABLE_ROW = 'ADD_VARIABLE_ROW'
export const POP_VARIABLE_ROW = 'POP_VARIABLE_ROW'

export const UPDATE_STEPS = 'UPDATE_STEPS'
export const UPDATE_CONFIGURATION = 'UPDATE_CONFIGURATION'

export const INCREASE_STEP = 'INCREASE_STEP'
export const DECREASE_STEP = 'DECREASE_STEP'
export const RESET_STEPS = 'RESET_STEPS'