// Query Graph
export const CHANGE_QUERY_GRAPH_TYPE = 'CHANGE_QUERY_GRAPH_TYPE'
export const CHANGE_QUERY_NUMBER_RELATIONS = 'CHANGE_QUERY_NUMBER_RELATIONS'
export const CHANGE_QUERY_GRAPH = 'CHANGE_QUERY_GRAPH'

// Algorithms
export const CHANGE_ALGORITHM = 'CHANGE_ALGORITHM'
export const UPDATE_ALGORITHMS = 'UPDATE_ALGORITHMS'

// Steps
export const UPDATE_STEPS = 'UPDATE_STEPS'
export const INCREASE_STEP = 'INCREASE_STEP'
export const DECREASE_STEP = 'DECREASE_STEP'
export const RESET_STEPS = 'RESET_STEPS'

export const UPDATE_STEP_UUID = 'UPDATE_STEP_UUID'

export const UPDATE_ROUTINES = 'UPDATE_ROUTINES'

export const UPDATE_GRAPH_STATE = 'UPDATE_GRAPH_STATE'

export const UPDATE_CONFIGURATION = 'UPDATE_CONFIGURATION'