// Query Graph
export const CHANGE_QUERY_GRAPH_TYPE = 'CHANGE_QUERY_GRAPH_TYPE'
export const CHANGE_QUERY_NUMBER_RELATIONS = 'CHANGE_QUERY_NUMBER_RELATIONS'

// Algorithm
export const CHANGE_ALGORITHM = 'CHANGE_ALGORITHM'